### ISSUE TITLE
Freecam only displaying player heads

### ISSUE THREAD

**Issue by CivetKitty** [maruohon/tweakeroo#175] opened 2021-02-21 16:46 UTC
![2021-02-22_01 42 59](https://user-images.githubusercontent.com/36259298/108631872-740c6400-74af-11eb-987e-e5a3c6d41be7.png)
![2021-02-22_01 43 18](https://user-images.githubusercontent.com/36259298/108631876-753d9100-74af-11eb-9568-4fc003a93bfe.png)
Freecam is only displaying player heads and nothing else. 
<img width="960" alt="mods" src="https://user-images.githubusercontent.com/36259298/108631912-ad44d400-74af-11eb-8929-22a84389e0b8.PNG">
I'm using 1.16.5 and here's my mods folder.

**Comment by maruohon** [comment] 2021-02-21 17:21
This is caused by something that Optifine does. I'm not going to try to figure out what it changes and how to get around that, since Optifine is even closed source.

**Comment by maruohon** [comment] 2021-03-13 12:55
This was fixed in the 2021-03-03 build for 1.16.4.

**Closed as completed by maruohon** 2021-03-13 12:55 UTC
Labels: mod-conflict, fixed-in-dev
