### ISSUE TITLE
Gamma Fix Not Saving Settings

### ISSUE THREAD

**Issue by iJevinYT** [maruohon/tweakeroo#376] opened 2022-09-28 12:23 UTC
When I sign onto my server Gamma is reverted.  Will toggle and it fixes.  Once I sign off and sign on it reverts.

Malilib 1.19.2 0.13.0
Minihud 1.19.2 0.23.3
Litematica 1.19.2 0.12.4
Itemscroller 1.19.2 0.17.1
Tweakeroo 1.19.2 0.14.3

**Comment by aditeya24** [comment] 2022-09-28 13:33
Issue is a duplicate of https://github.com/maruohon/tweakeroo/issues/348

**Comment by maruohon** [comment] 2022-10-07 21:56
Closing as duplicate

**Closed as completed by maruohon** 2022-10-07 21:56 UTC
Labels: bug (minor)
